# see http://www.appveyor.com/docs/appveyor-yml

##### ENABLE REMOVE RDP ACCESS #####
# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#######################

install:
  # C++ Requires importing vcvars: https://www.appveyor.com/docs/lang/cpp/#visual-studio-2015
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

#---------------------------------#
#      build configuration        #
#---------------------------------#
build_script:
 - cmd: 'msbuild .\.build\libmspack4n.msbuild /p:TheVersion="%APPVEYOR_BUILD_VERSION%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test:
  assemblies:
    - .deploy\libmspack4ntest.dll

artifacts:
- path: '.deploy\nuget-package\*.nupkg'
- path: '.deploy\*.zip'

deploy:
  - provider: GitHub # See https://www.appveyor.com/docs/deployment/github/
    release: v$(APPVEYOR_BUILD_VERSION)
    description: 'Appveyor deployed v$(APPVEYOR_BUILD_VERSION)'
    auth_token:
      secure: Ocl+kToBlL/IWT9+682+RyT3guxvjf/ZROODM+yt9BIAQaRu3xuKTATThJe9+Vuw # from https://github.com/settings/tokens; encrypted at https://ci.appveyor.com/tools/encrypt
    artifact: /(.*\.nupkg)|(.*\.zip)/ # upload NuGet & zip files to release assets
    draft: false
    prerelease: false
    on:
      branch: master                  # only deploy on master
      appveyor_repo_tag: true         # only deploy when there is a tag pushed
      appveyor_repo_tag_name: publish # only deploy when tag == "publish"
  
  - provider: NuGet # See https://www.appveyor.com/docs/deployment/nuget/
    api_key:
      secure: 9elIHDxuSEIvn/us9M5SmtAatYvwZO++m8dYABofIt+/2xcLpuz1Qv9DkypOzpeU # from https://www.nuget.org/account/apikeys; encrypted at https://ci.appveyor.com/tools/encrypt
    artifact: /.*\.nupkg/
    on:
      branch: master                  # only deploy on master
      appveyor_repo_tag: true         # only deploy when there is a tag pushed
      appveyor_repo_tag_name: publish # only deploy when tag == "publish"

on_finish:
  - cmd: 'dir /s %APPVEYOR_BUILD_FOLDER%\.deploy'
  - cmd: 'dir /s %APPVEYOR_BUILD_FOLDER%\libmspack4ntest\bin\Release'
##### KEEP RDP ACCESS #####
# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#######################